### ISSUE TITLE
git-autoshare never triggered?

### ISSUE THREAD

**Issue by rvalyi** [acsone/git-aggregator#26]
Hello @sbidoul. I like both your git-aggregator and git-autoshare tools. However, git-aggregator triggers `git init` and `git fetch` but never the `git clone` command (see https://github.com/acsone/git-aggregator/blob/master/git_aggregator/repo.py ).
So git-autoshare will never get triggered unless you do a git clone of the repo previously before calling git-aggregator.
Woudn't there be a way to trigger git clone/git-autoshare when the repo is empty at least?
What do you think?

**Comment by sbidoul** [comment]
That needs investigation. Does not sound trivial at first glance.

Note that we don't really suffer much about this in our workflow, because git-aggregate is infrequent, comparing to git cloning of frozen references (aka pip install requirements.txt :). git-aggregate is typically done at the beginning of a development cycle to refresh base versions of unmerged PRs.

**Comment by rvalyi** [comment]
@sbidou. Yes it's also infrequent for us. Today it's just about remembering to do a git clone manually when starting a nez Docky project. Eventually we doo that in akretion/ak, I will check with the rest of the team and confirm if we can tackle it this way.

**Comment by sbidoul** [comment]
This was resolved in https://github.com/acsone/git-aggregator/pull/55

**Comment by rvalyi** [comment]
thanks, BTW both tools absolutely rock!

**Comment by rvalyi** [comment]
just a message to confirm my tests show it was really fixed. Thanks again.
